### PR TITLE
improve POD, mention RT issues

### PR DESCRIPTION
**Pull request by asb-capfan**
Applied spelling corrections as mentioned in RT #84896. Added info about
RT #84318 which was fixed in commit on 2015-01-15. Added links in SEE
ALSO section. Added a test for POD correctness.

Who closes the RT issues that have been solved?

### CODE REVIEW

**Comment by neilb** [comment]
Hi,

Thanks for this.

Can you make the pod test only apply for release testing please (if the `RELEASE_TESTING` env variable is set to a true value)? A pod error shouldn't prevent a dist installing.

Cheers,
Neil

**Comment by asb-capfan** [comment]
Good point, it's done.

**Comment by neilb** [comment]
Thanks -- I'll do a final check this evening, and if all is good, will merge and release tonight.

Thanks again.

**Comment by neilb** [comment]
Thanks!

**Comment by neilb** [comment]
Version 1.68 making its way to CPAN.

**Comment by handikafranata** [comment]
asb-cpan

**Pull request merged**
